spring:
  datasource:
    url: jdbc:h2:mem:platform;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

app:
  ui:
    admin-url: http://localhost:5173/admin
    downloader-url: http://localhost:5173/app/downloader
  worker:
    redis-enabled: false
